apiVersion: v1 # When was thePod introduced in Kubernetes? v1.0
kind: Pod # Wat are we starting? A Pod
metadata:
  name: next # Name of the Pod
  namespace: 100x-devs
  labels:
    app: next
spec:
  containers:
    - name: next # First container to start inside the POD
      image: parth3083/gitops-practice:06416240efc937f1cb134b78b3362fb5dc2ee8ce
      ports:
      - containerPort: 80  # Port on which Pod will listen for incoming requests